name: Build and Push Laravel Installer Image to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile-installer'
      - '.github/workflows/build-and-push-installer.yml'
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push installer (Laravel 10, 11, 12, PHP 8.3)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-installer
          push: true
          tags: ghcr.io/redfieldchristabel/laravel:installer
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max