name: Build and Push Laravel Images to GHCR

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  push:
    branches:
      - main # Trigger on push to main for testing
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        php_version: ['8.3']
        variant: ['fpm-alpine']
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/laravel
          tags: |
            type=raw,value=${{ matrix.php_version }}-${{ matrix.variant }}
            type=raw,value=${{ matrix.php_version }},enable=${{ matrix.variant == 'cli' }}
            type=raw,value=${{ matrix.variant }},enable=${{ matrix.php_version == '8.4' }}
            type=raw,value=latest,enable=${{ matrix.php_version == '8.4' && matrix.variant == 'cli' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.variant == 'alpine' || matrix.variant == 'fpm-alpine' && 'Dockerfile.alpine' || 'Dockerfile.debian' }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            VARIANT=${{ matrix.variant == 'alpine' && 'cli' || matrix.variant == 'fpm-alpine' && 'fpm' || matrix.variant }}
          target: ${{ matrix.variant == 'fpm' || matrix.variant == 'fpm-alpine' && 'fpm' || 'cli' }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify pushed image
        run: |
          docker pull ghcr.io/${{ github.repository }}/laravel:${{ matrix.php_version }}-${{ matrix.variant }}
          echo "Successfully pulled ghcr.io/${{ github.repository }}/laravel:${{ matrix.php_version }}-${{ matrix.variant }}"