name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          path: cli
          release-type: dart
      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"

  build-release-assets:
    needs: release-please
    if: ${{ needs.release-please.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        working-directory: ./cli # Target the cli folder
        run: dart pub get

      - name: Generate Assets
        working-directory: ./cli
        run: dart run tool/generate_assets.dart

      - name: Compile CLI
        working-directory: ./cli
        run: |
          mkdir -p build
          dart compile exe bin/cli.dart -o build/cli.sh

      - name: Upload Binary to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} ./cli/build/cli.sh --clobber